import { Database } from './database.js';

export const SWBF_DB = new Database({
    Organisation: ['Name'],
    Season: [
        'ID',
        'OrganisationName',
        'Name',
        'ShortName',
        'Group',
        'Colour',
        'TournamentMode',
        'TeamCap',
    ],
    Team: ['Name', 'ShortName', 'PrimColour', 'SecColour'],
    PlayedFor: [
        'TeamName',
        'SeasonID',
        'PlayerName',
        'Rating',
        'IsCaptain',
        'IsPrimary',
        'RebelImage',
        'ImperialImage',
        'CardStatsID',
    ],
    Player: ['Name', 'Nationality'],
    Series: ['Index', 'Round'],
    Match: [
        'MatchID',
        'SeriesIndex',
        'MatchIndex',
        'GameMode',
        'Map',
        'Server',
        'Duration',
    ],
    PlayerScore: [
        'MatchID',
        'PlayerName',
        'Score',
        'Kills',
        'Deaths',
        'Duration',
    ],
    TeamScore: [
        'MatchID',
        'TeamName',
        'Fraction',
        'Score',
    ],
    SeriesIn: ['SeasonID', 'SeriesIndex', 'SeriesRound'],
    Award: [
        'SeasonID',
        'SeriesIndex',
        'PlayerName',
        'AwardType',
        'CardStats',
        'RebImage',
        'ImpImage',
    ],
    CardStats: [
        'CardStatsID',
        'CardRating',
        'Offence',
        'Defence',
        'KDR',
        'Objective',
        'Positioning',
        'Intelligence',
    ],
});